---
title: "Map matching"
format: html
---

## Purpose

Match parish name to map of parish from histmaps 

```{r}
# devtools::install_github("https://github.com/junkka/histmaps")
library(histmaps)
library(sf)
library(tidyverse)
```

```{r}
# ??get_boundaries

```

```{r}
map <- get_boundaries(1900, "parish")
plot(st_geometry(map))


```

```{r}
data("geom_meta")

parishs_map <- geom_meta %>% 
  filter(type_id == "parish",
         county == 1,
         from < 1900,
         tom > 1900) %>% 
    # select(parish = name.x) %>% 
    rename(parish = name.x) %>% 
    mutate(parish = str_remove_all(parish, "församling"),
           parish = str_remove_all(parish, "\\(AB-län\\)"),
           parish = str_squish(parish))



df_parish_names <- read_rds(here::here("data", "parish_names_from_aws.rds"))

ids <- parishs_map %>% 
    inner_join(df_parish_names)
```

So these 80 are the ones that co-occur in our dataset and the maps

Now we need to join up the data from the agric stats with the map files


How do we analyse this?

```{r}
library(tidyverse)

get_file_names <- function(year) {
  list.files(path = glue::glue("{year}/"), pattern = "*.rds") %>%
    str_c(glue::glue("{year}/"), .) %>% as_tibble()
}


list_of_files <- get_file_names(1865) %>% 
    bind_rows(get_file_names(1890)) %>% 
    bind_rows(get_file_names(1900)) %>% 
    bind_rows(get_file_names(1911))

df <-
    list_of_files %>% pull(value) %>% 
    map_df(~read_rds(.))


```



```{r}
map <- ids %>% 
    inner_join(map)

map_2 <- df %>%
    mutate(parish = str_squish(parish)) %>%
    inner_join(map)

# stockholm <- data.frame(longitude = c(59.3293), latitude = c(18.0686), label = "Stockholm")

stockholm <- st_as_sf(stockholm, coords = c("longitude", "latitude"), 
    crs = "SWEREF99", agr = "constant")

plot_col <- function(col_in) {
   map_2 %>%
    filter(col == col_in) %>%
    ggplot(aes(geometry = geometry, fill = value)) +
    geom_sf() +
    # geom_sf(data = stockholm, size = 4, shape = 23, fill = "darkred") +
    scale_fill_gradient2(low = "blue", high = "red", mid = "pink", midpoint = 400) +
    labs(subtitle = glue::glue("Column index: {col_in}"))
}
```


```{r}
plot_col(2) +
  labs(title = "Number of taxpayers")
```



```{r}
plot_col(13) +
  labs(title = "Agricultural land")
```

```{r}
plot_col(78) +
  labs(
    title = "Horses by parish in Stockholm in 1900",
    fill = "Number of horses"
  ) +
  theme_void()
```

```{r}
plot_col(3) +
  labs(
    title = "Horses by parish in Stockholm in 1900",
    fill = "Number of horses"
  ) +
  theme_void()
```





